<a href="https://colab.research.google.com/github/aditya-account/Colab/blob/main/MachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive


#Mounting to Drive

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/')

#List out All Files in Drives 

In [ ]:
!ls

sample_data


In [ ]:
!ls "/content/gdrive/My Drive"

 AOS_Scanned_Certficates.rar
'Colab Notebooks'
'Copy of Final Participants _Certificaiton.xlsx'
 deepfake-detection-challenge.zip
'Dr. A. Obulesh.gsite'
 draos.jpg
 Dr_AOS_Resume_F.docx
 features.csv
'Final Participants _Certificaiton.xlsx'
'Getting started.pdf'
'Google Earth'
 Lit.rar
'Meet Attendance 2020-7-27 11:54 (1).gsheet'
'Meet Attendance 2020-7-27 11:54.gsheet'
 ML
 PL_F_Resume_DrAOS.docx
 target.csv
'Untitled Jam.gjam'
'Untitled site.gsite'


#Another way of loading file in colab

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
!pwd

/gdrive


In [ ]:
import pandas as pd
from google.colab import drive

drive.mount('/content/gdrive', force_remount=True)


Mounted at /content/gdrive


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#Simple Machine Learning Models for Predicting Cardio risk predicting 

In [ ]:
from numpy import histogramdd
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics

F =pd.read_csv('/content/drive/MyDrive/features.csv')
T =pd.read_csv('/content/drive/MyDrive/target.csv')
print(F.shape)
print(T.shape)
X_train, X_test, Y_train, Y_test = train_test_split(F,T, test_size=0.2, train_size=0.8, random_state=0)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)



from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()


Z= log_reg.fit( X_train,Y_train.values.ravel())

print(X_test[10:20])
l = log_reg.predict(X_test[10:20])
print(l)

l=log_reg.score(X_test,histogramdd)
print(l)





(296, 13)
(296, 1)
(236, 13)
(60, 13)
(236, 1)
(60, 1)
     Age   Gender   Cptype   BloodPressure   Cholestrol  FastingBloodSugar  \
295   57        0        2             130          236                  0   
15    48        1        2             110          229                  0   
146   45        1        2             128          308                  0   
223   67        0        3             152          277                  0   
22    58        1        3             132          224                  0   
235   42        1        2             120          295                  0   
219   53        1        4             123          282                  0   
268   71        0        4             112          149                  0   
66    54        1        3             150          232                  0   
111   43        0        4             132          341                  1   

     EcgResults   MaxHeartRate   Exang   STDepression   Slope   ca   Thal  
295       

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [ ]:
#Importing of Libraries 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
#import matplotlib.pyplot as plt
#from sklearn.feature_selection import RFE
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
#Loading Dataset
features = pd.read_csv('/content/gdrive/My Drive/features.csv')
target = pd.read_csv('/content/gdrive/My Drive/target.csv')


In [ ]:
#Finding of True facts of DataSet
print('Features Dataset')
print(features.tail())
print('Target Dataset')
print(target.head())
print(features.shape)
print(target.shape)
print('Feature Names of Features Dataset')
print(features.keys())
print('Features Names of Target Dataset')
print(target.keys())

Features Dataset
     Age   Gender   Cptype   BloodPressure  ...   STDepression   Slope   ca   Thal
291   57        0        4             140  ...            0.2       2    0      7
292   45        1        1             110  ...            1.2       2    0      7
293   68        1        4             144  ...            3.4       2    2      7
294   57        1        4             130  ...            1.2       2    1      7
295   57        0        2             130  ...            0.0       2    1      3

[5 rows x 13 columns]
Target Dataset
    status
0        2
1        1
2        0
3        0
4        0
(296, 13)
(296, 1)
Feature Names of Features Dataset
Index(['Age', ' Gender', ' Cptype', ' BloodPressure', ' Cholestrol',
       'FastingBloodSugar', 'EcgResults', ' MaxHeartRate', ' Exang',
       ' STDepression', ' Slope', ' ca', ' Thal'],
      dtype='object')
Features Names of Target Dataset
Index([' status'], dtype='object')


In [ ]:
#Spliting dataset into Training and Testing 
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(features,target, test_size=0.2, train_size=0.8, random_state=0)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(236, 13)
(60, 13)
(236, 1)
(60, 1)


In [ ]:
#Logistic regression

from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
print(log_reg)
#log_reg.fit(X_train,Y_train.values.ravel())

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)


In [ ]:
#Train the model with given Training dataset

print(log_reg.fit(X_train,Y_train.values.ravel()))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
#Measure the SCore
l=log_reg.score(X_test,Y_test)
print(l)


0.6166666666666667


In [ ]:
#Predicting of Testing Data
l=log_reg.predict(X_train[10:20])
print(X_train[10:20])
print(l)

     Age   Gender   Cptype   BloodPressure  ...   STDepression   Slope   ca   Thal
221   34        0        2             118  ...            0.7       1    0      3
255   57        1        2             124  ...            0.3       1    0      7
37    55        1        4             132  ...            1.2       2    1      7
226   52        0        3             136  ...            0.1       2    0      3
158   46        1        2             101  ...            0.0       1    0      7
89    62        0        4             160  ...            6.2       3    3      7
286   44        1        4             120  ...            2.8       3    0      6
156   60        1        4             140  ...            1.2       2    2      7
271   66        0        3             146  ...            0.0       2    1      3
108   61        0        4             145  ...            1.0       2    0      7

[10 rows x 13 columns]
[0 1 1 0 0 3 1 1 0 1]


In [ ]:
#Importing of Libraries 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.feature_selection import RFE
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Loading Dataset
features = pd.read_csv('/content/gdrive/My Drive/features.csv')
target = pd.read_csv('/content/gdrive/My Drive/target.csv')

#Finding of True facts of DataSet
print('Features Dataset')
print(features.head())
print('Target Dataset')
print(target.head())
print(target.shape)
print(features.shape)
print('Feature Names of Features Dataset')
print(features.keys())
print('Features Names of Target Dataset')
print(target.keys())

#Spliting dataset into Training and Testing 
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(features,target,test_size=0.2, train_size=0.8, random_state=0)
print(X_test.shape)
print(Y_test.shape)
print(X_train.shape)
print(Y_train.shape)

#Logistic regression

from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
print(log_reg)

log_reg.fit(X_train,Y_train.values.ravel())
  
#Train the model with given Training dataset

print(log_reg.fit(X_train,Y_train.values.ravel()))
    
#Measure the SCore
l=log_reg.score(X_test,Y_test)
print(l)

#Predicting of Testing Data
l=log_reg.predict(X_train[10:20])
print(l)

print("Dr. AOS")


FileNotFoundError: ignored

# KNeighborsClassifier On Same Case Study 

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier()
knn_clf.fit(X_train, Y_train)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  after removing the cwd from sys.path.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
l=knn_clf.predict(X_train[10:20])
print(l)

[0 0 0 0 0 2 0 0 0 0]


In [ ]:
l=knn_clf.score(X_test,Y_test)
print(l)

0.5166666666666667


#SGDClassifier on Same Case Study ...


In [ ]:
#train the model

from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier(random_state=42)
#sgd_clf.fit(X_train, y_train_5)
sgd_clf.fit(X_train, Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=42, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [ ]:
# testing the model
#print(X_train.shape, X_train.size)
y_pred = sgd_clf.predict(X_test)
print(y_pred)


[2 2 0 2 0 2 2 2 2 2 0 0 2 2 2 2 2 2 2 2 0 2 2 2 0 0 0 2 2 2 2 0 2 2 2 2 2
 0 2 2 2 2 2 2 2 0 2 2 2 0 2 2 2 0 2 0 2 0 0 2]


In [ ]:
c=sgd_clf.score(X_test, Y_test)
print(c)


0.3333333333333333


#Cross Validation Evaluation...


In [ ]:
# Cross validation

from sklearn.model_selection import cross_val_score
#splitting the training instance into k-folds, 
#A model is trained using k-1 of the folds as training data
#he resulting model is validated on the remaining part of the data
cross_val_score(sgd_clf, X_train, Y_train, cv=5, scoring="accuracy")

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

array([0.5625    , 0.55319149, 0.59574468, 0.53191489, 0.53191489])

In [ ]:
# Confusion Matrix


# cross val predict performs k-fold cross-validation, but instead of returning the evaluation scores, it returns prediction ma
from sklearn.model_selection import cross_val_predict

y_train_pred = cross_val_predict(sgd_clf, X_train, Y_train, cv=3)
#y_train_pred = cross_val_predict(sgd_clf, X_test, cv=3)
print(y_train_pred)


from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_train, y_train_pred)
print("Confusion Matrix")
print(matrix)

[1 0 0 0 1 1 1 0 1 0 0 1 1 0 0 1 0 1 1 1 1 1 1 0 1 0 0 0 1 0 1 1 0 0 1 1 0
 1 1 1 1 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 1 1 1 0 0 0 0 1 1 0 0 1 1
 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0
 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0 0 0 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 3]
Confusion Matrix
[[88 39  0  0  0]
 [19 24  0  1  0]
 [10 17  0  0  0]
 [10 19  0  1  0]
 [ 4  4  0  0  0]]


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
# Precision and Recall

from sklearn.metrics import precision_score, recall_score

print("Precision:", precision_score(Y_train, y_train_pred, average='micro'))

print("Recall:", recall_score(Y_train, y_train_pred,average='micro'))


Precision: 0.4788135593220339
Recall: 0.4788135593220339


In [ ]:
# F1 score - harmonic mean of precision and recall

from sklearn.metrics import f1_score
print("F1 score:", f1_score(Y_train, y_train_pred, average='micro'))

F1 score: 0.4788135593220339


# SupportVector Machine (SVM)

In [ ]:
# we create an instance of SVM and fit out data. We do not scale our
# data since we want to plot the support vectors
C = 1.0 # SVM regularization parameter
from sklearn import svm, datasets
svc = svm.SVC(kernel='linear', C=1).fit(X_train, Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
svc = svm.SVC(kernel='rbf', C=1).fit(X_train, Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
c=svc.score(X_test, Y_test)
print(c)

0.5333333333333333
